config/routes.rb
Dataflux::Application.routes.draw do

  root :to => "home#index"

  match "enlaces-de-interes" => "enlaces#index", :as=>"enlaces"
  match "soporte-y-descargas" => "soporte#index", :as=>"soporte"
  match "contacto" => "contacto#index"
  match "contacto-submit" => "contacto#submit"

  match "quienes-somos" => "acerca_de#index", :as=>"acerca_de"
  match "servicios-web" => "servicios_web#index", :as=>"web"
  match "soluciones-cloud" => "soluciones_cloud#index", :as=>"cloud"
  match "proyectos-tic" => "proyectos_tic#index", :as=>"tic"

  match "sitemap" => "sitemap#index"

end

app/controllers/acerca_de_controller.rb
class AcercaDeController < ApplicationController
end

app/controllers/application_controller.rb
# encoding: utf-8;

class ApplicationController < ActionController::Base

  protect_from_forgery
  helper_method :date_to_es, :parallax_offset, :mobile_device?

#  before_filter :load_tweets
  before_filter :prepare_for_mobile

  def date_to_es(datestring)
    return datestring.gsub("Monday","Lunes").gsub("Tuesday","Martes").gsub("Wednesday","Miércoles").gsub("Thursday","Jueves").gsub("Friday","Viernes").gsub("Saturday","Sábado").gsub("Sunday","Domingo").gsub("January","Enero").gsub("February","Febrero").gsub("March","Marzo").gsub("April","Abril").gsub("May","Mayo").gsub("June","Junio").gsub("July","Julio").gsub("August","Agosto").gsub("September","Septiembre").gsub("October","Octubre").gsub("November","Noviembre").gsub("December","Diciembre")
  end

  def parallax_offset
    "200"
  end

  def mobile_device?
    if session[:mobile_param]
      session[:mobile_param] == "1"
    else
      request.user_agent =~ /Mobile|webOS/
    end
  end

  def prepare_for_mobile
    session[:mobile_param] = params[:mobile] if params[:mobile]
    request.format = :mobile if mobile_device?
  end

#  def load_tweets
#    @twitter_user = "dataflux"
#    Rails.cache.fetch(@twitter_user, :expires_in => 10.minutes) do
#      status = Twitter.user(@twitter_user).status
#      @last_tweet = format_tweet(status)
#    end
#  end

#  def format_tweet(status)
#    @entities = []
#    status.urls.each do |url|
#      @entities.append [ url.url, url.url ]
#    end
#    status.user_mentions.each do |um|
#      @entities.append [ "@"+um.screen_name, "http://twitter.com/"+um.screen_name ]
#    end
#    status_text = status.text
#    @entities.each do |e|
#      status_text = status_text.gsub(e.first, "<a href='"+e.second+"' target='_blank'>"+e.first+"</a>")
#    end
#    return [ status_text, status.created_at, status.id ]
#  end

end

app/controllers/contacto_controller.rb
class ContactoController < ApplicationController

  def submit
    if params[:authenticity_token]
      ContactoMailer.forward_submit(params).deliver
    else
      redirect_to root_path
    end
  end

end

app/controllers/enlaces_controller.rb
class EnlacesController < ApplicationController

  def index
    @graph = Koala::Facebook::API.new "468664856582683|IzVB_5mOvHjOaXY2ZaNIPhrJodA"
    @feed = @graph.get_connections("dataflux", "feed", :limit=>10)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @scroller_marcas = [
      "aerohive.png",
      "aruba.png",
      "asterisk.png",
      "cisco.png",
      "mikrotik.png",
      "ruckus.png",
      "ubiquiti.png"
    ]
    @scroller_clientes = [
      "aeronautica_civil.png",
      "aluminaire.png",
      "charter.png",
      "colegio_hebreo.png",
      "country_plaza.png",
      "easy_soat.png",
      "gsp.png",
      "lemon.png",
      "lex_tattoo.png",
      "miramar.png",
      "pasteur.png",
      "perfect_beauty.png",
      "protecnica.png",
      "satec.png",
      "stewart_stevenson.png",
      "thermo_coil.png",
      "transporte_ejecutivo.png",
      "uribe_largacha.png",
      "villa_country.png"
    ]
  end

end

app/controllers/proyectos_tic_controller.rb
class ProyectosTicController < ApplicationController
end

app/controllers/servicios_web_controller.rb
class ServiciosWebController < ApplicationController
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController

  def index
    redirect_to "https://sitemaps-bucket.s3.amazonaws.com/sitemaps/sitemap.xml.gz"
  end

end

app/controllers/soluciones_cloud_controller.rb
class SolucionesCloudController < ApplicationController
end

app/controllers/soporte_controller.rb
class SoporteController < ApplicationController
end

app/views/acerca_de/_nuestros_servicios.html.erb
<h2 id="nuestros-servicios" class="withLEDs">Nuestros Servicios</h2>

<h3>Web</h3>
<ul class="extraspaceXL servicios">
  <li><span><%=link_to "Dominios",web_path(:anchor=>"dominios")%> (<strong>.com</strong> <strong>.co</strong>, entre muchos otros)</span></li>
  <li><span>Alojamiento web (<%=link_to "Hosting",web_path(:anchor=>"hosting")%>)</span></li>
  <li><span>Administración y Mantenimiento de sitios web (<%=link_to "Webmastering",web_path(:anchor=>"webmaster")%>)</span></li>
  <li><span>Alojamiento y Streaming de Multimedia (<%=link_to "Audio Streaming",web_path(:anchor=>"streaming-audio")%> y <%=link_to "Video Streaming",web_path(:anchor=>"streaming-video")%>)</span></li>
  <li><span><%= link_to "Diseño y Desarrollo de Sitios Web", web_path(:anchor=>"webdev") %></span>
    <ul class="servicios compact">
      <li><span>Sitios web principalmente informativos (<%=link_to "Plan Starter",web_path(:anchor=>"webdev-plans")%>)</span></li>
      <li><span>Para pequeñas empresas o negocios (<%=link_to "Plan Basic",web_path(:anchor=>"webdev-plans")%>)</span></li>
      <li><span>Para medianas y grandes empresas (<%=link_to "Plan Plus",web_path(:anchor=>"webdev-plans")%>)</span></li>
      <li><span>Aplicación Web totalmente personalizada (<%=link_to "Plan Pro",web_path(:anchor=>"webdev-plans")%>)</span></li>
    </ul>
  </li>
</ul>

<h3>Cloud</h3>
<ul class="extraspaceXL servicios enconstruccion">
  <li><span><%=link_to "Servidores Privados Virtuales (VPS)",cloud_path(:anchor=>"vps")%></span></li>
  <li><span><%=link_to "Hosting en VPS (Cloud Hosting)",cloud_path(:anchor=>"cloud-hosting")%></span></li>
  <li><span> <%=link_to "Gaming Servers",cloud_path(:anchor=>"gaming-servers")%> </span></li>
  <li><span> <%=link_to "Telefonía IP en la Nube",cloud_path(:anchor=>"telefonia-ip-nube")%> </span></li>
  <li><span> <%=link_to "Contabilidad en la Nube",cloud_path(:anchor=>"contabilidad-nube")%> </span></li>
</ul>

<h3>Tecnología de la Información y las Comunicaciones (TIC)</h3>
<ul class="extraspaceXL servicios enconstruccion">
  <li><span><%=link_to "Asesoría",tic_path(:anchor=>"asesoria")%> en sistemas TIC</span></li>
  <li><span><%=link_to "Consultoría",tic_path(:anchor=>"consultoria")%> en sistemas TIC</span></li>
  <li><span><%=link_to "Tercerización",tic_path(:anchor=>"tercerización")%> TIC (Manejo de Infraestructura)</span></li>
  <li><span>Puesta en marcha de <%=link_to "Servidores Linux",tic_path(:anchor=>"servidores-linux")%></span></li>
  <li><span>Diseño de <%=link_to "Redes de datos",tic_path(:anchor=>"redes")%></span>
    <ul class="servicios compact">
      <li><span>Enlaces de datos cableados o inalámbricos de corto y largo alcance</span></li>
      <li><span>Implementación de políticas y normativas de seguridad informática</span></li>
      <li><span>Puesta en marcha de sistemas de redes de computación (<strong>Firewall</strong>, <strong>IDS</strong>, <strong>IPS</strong>, <strong>DHCP</strong>, <strong>Autenticación</strong>, entre otros)</span></li>
      <li><span>Configuración de <strong>Routers</strong>, <strong>Switches</strong> y <strong>Access Points (APs)</strong></span></li>
      <li><span><strong>Hotsposts</strong> (Zonas de <strong>WiFi</strong> en áreas públicas)</span></li>
    </ul>
  </li>
  <li><span>Puesta en marcha de <%=link_to "Sistemas de Telefonía IP",tic_path(:anchor=>"telefonia-ip")%></span></li>
</ul>
<br>

<p>Esperamos ser la solución a sus necesidades, con las herramientas hechas a su medida para así ofrecerle calidad y profesionalismo.</p>

app/views/acerca_de/_nuestros_servicios.mobile.erb
<h2 id="nuestros-servicios" class="withLEDs">Nuestros Servicios</h2>

<h3>Web</h3>
<ul class="extraspaceXL servicios">
  <li><span><%=link_to "Dominios",web_path(:anchor=>"dominios")%> (<strong>.com</strong> <strong>.co</strong>, entre muchos otros)</span></li>
  <li><span>Alojamiento web (<%=link_to "Hosting",web_path(:anchor=>"hosting")%>)</span></li>
  <li><span>Administración y Mantenimiento de sitios web (<%=link_to "Webmastering",web_path(:anchor=>"webmaster")%>)</span></li>
  <li><span>Alojamiento y Streaming de Multimedia (<%=link_to "Audio Streaming",web_path(:anchor=>"streaming-audio")%> y <%=link_to "Video Streaming",web_path(:anchor=>"streaming-video")%>)</span></li>
  <li><span><%= link_to "Diseño y Desarrollo de Sitios Web", web_path(:anchor=>"webdev") %></span>
    <ul class="servicios compact">
      <li><span>Sitios web principalmente informativos (<%=link_to "Plan Starter",web_path(:anchor=>"webdev-plans")%>)</span></li>
      <li><span>Para pequeñas empresas o negocios (<%=link_to "Plan Basic",web_path(:anchor=>"webdev-plans")%>)</span></li>
      <li><span>Para medianas y grandes empresas (<%=link_to "Plan Plus",web_path(:anchor=>"webdev-plans")%>)</span></li>
      <li><span>Aplicación Web totalmente personalizada (<%=link_to "Plan Pro",web_path(:anchor=>"webdev-plans")%>)</span></li>
    </ul>
  </li>
</ul>

<h3>Cloud</h3>
<ul class="extraspaceXL servicios enconstruccion">
  <li><span><%=link_to "Servidores Privados Virtuales (VPS)",cloud_path(:anchor=>"vps")%></span></li>
  <li><span><%=link_to "Hosting en VPS (Cloud Hosting)",cloud_path(:anchor=>"cloud-hosting")%></span></li>
  <li><span> <%=link_to "Gaming Servers",cloud_path(:anchor=>"gaming-servers")%> </span></li>
  <li><span> <%=link_to "Telefonía IP en la Nube",cloud_path(:anchor=>"telefonia-ip-nube")%> </span></li>
  <li><span> <%=link_to "Contabilidad en la Nube",cloud_path(:anchor=>"contabilidad-nube")%> </span></li>
</ul>

<h3>Tecnología de la Información y las Comunicaciones (TIC)</h3>
<ul class="extraspaceXL servicios enconstruccion">
  <li><span><%=link_to "Asesoría",tic_path(:anchor=>"asesoria")%> en sistemas TIC</span></li>
  <li><span><%=link_to "Consultoría",tic_path(:anchor=>"consultoria")%> en sistemas TIC</span></li>
  <li><span><%=link_to "Tercerización",tic_path(:anchor=>"tercerización")%> TIC (Manejo de Infraestructura)</span></li>
  <li><span>Puesta en marcha de <%=link_to "Servidores Linux",tic_path(:anchor=>"servidores-linux")%></span></li>
  <li><span>Diseño de <%=link_to "Redes de datos",tic_path(:anchor=>"redes")%></span>
    <ul class="servicios compact">
      <li><span>Enlaces de datos cableados o inalámbricos de corto y largo alcance</span></li>
      <li><span>Implementación de políticas y normativas de seguridad informática</span></li>
      <li><span>Puesta en marcha de sistemas de redes de computación (<strong>Firewall</strong>, <strong>IDS</strong>, <strong>IPS</strong>, <strong>DHCP</strong>, <strong>Autenticación</strong>, entre otros)</span></li>
      <li><span>Configuración de <strong>Routers</strong>, <strong>Switches</strong> y <strong>Access Points (APs)</strong></span></li>
      <li><span><strong>Hotsposts</strong> (Zonas de <strong>WiFi</strong> en áreas públicas)</span></li>
    </ul>
  </li>
  <li><span>Puesta en marcha de <%=link_to "Sistemas de Telefonía IP",tic_path(:anchor=>"telefonia-ip")%></span></li>
</ul>
<br>

<p>Esperamos ser la solución a sus necesidades, con las herramientas hechas a su medida para así ofrecerle calidad y profesionalismo.</p>

app/views/home/index.html.erb
<h1 style="display:none;">Dataflux - Home</h1>

<div id="home-content" class="section_content"><div class="wrapper">
  <div class="sectionbox homebox trails first"><span>
    <h2 class="withLEDs">INFRAESTRUCTURA ROBUSTA</h2>
    <p>Nuestros servicios corren en nuestros propios servidores, ubicados en distintos datacenters del mundo, bajo una infrastructura segura y redundante.</p>
    <%= link_to "VER MÁS", acerca_de_path %>
  </span></div>
  <br>
  <br>
  <div class="sectionbox homebox trails second"><span>
    <h2 class="withLEDs">TUS IDEAS EN SOLUCIONES</h2>
    <p>Diseñamos y ponemos en marcha proyectos que incluyen servidores, telefonía IP, redes de computación y enlaces de pequeño a gran alcance.</p>
    <%= link_to "VER MÁS", tic_path %>
  </span></div>
  <br>
  <br>
  <div class="sectionbox homebox trails third"><span>
    <h2 class="withLEDs">CONTAMOS CON EXPERIENCIA</h2>
    <p>Nuestro personal está capacitado y certificado en distintas áreas de la industria IT.</p>
    <%= link_to "VER MÁS", acerca_de_path(:anchor=>"certificaciones") %>
  </span></div>
</div></div>

<%#= render :partial => "social" %>

<%= render :partial => "marcas_y_clientes" %>

app/views/home/index.mobile.erb
<h1 style="display:none;">Dataflux - Home</h1>

<div id="home-content" class="section_content"><div class="wrapper">
  <div class="sectionbox trails first"></div>
  <div class="sectionbox homebox first">
    <span>
      <h2 class="withLEDs">INFRAESTRUCTURA ROBUSTA</h2>
      <p>Nuestros servicios corren en nuestros propios servidores, ubicados en distintos datacenters del mundo, bajo una infrastructura segura y redundante.</p>
      <%= link_to "VER MÁS", acerca_de_path %>
    </span>
  </div>
  <br>
  <br>
  <div class="sectionbox trails second"></div>
  <div class="sectionbox homebox second"><span>
    <h2 class="withLEDs">TUS IDEAS EN SOLUCIONES</h2>
    <p>Diseñamos y ponemos en marcha proyectos que incluyen servidores, telefonía IP, redes de computación y enlaces de pequeño a gran alcance.</p>
    <%= link_to "VER MÁS", tic_path %>
  </span></div>
  <br>
  <br>
  <div class="sectionbox trails third"></div>
  <div class="sectionbox homebox third"><span>
    <h2 class="withLEDs">CONTAMOS CON EXPERIENCIA</h2>
    <p>Nuestro personal está capacitado y certificado en distintas áreas de la industria IT.</p>
    <%= link_to "VER MÁS", acerca_de_path(:anchor=>"certificaciones") %>
  </span></div>
</div></div>

<%= render :partial => "marcas_y_clientes" %>

app/views/layouts/_header.html.erb
<div id="header">

  <%= render :partial => "layouts/headertoptabs" %>

  <div id="headerbottom"><div class="wrapper">
    <%= link_to image_tag("logo_header.png"), root_path, :id=>"logoheader" %>
    <%= render :partial => "layouts/headerbottomtabs" %>
  </div></div>

</div>

<%= render :partial => "layouts/stickyheader" %>

app/views/layouts/_headerbottomtabs.html.erb
<div id="headerbottomtabs">

  <span class="hbtwrapper">
    <%= link_to "Quiénes Somos", acerca_de_path(:anchor=>"head"), :class=>(controller.controller_name=="acerca_de" ? "hbt active" : "hbt"), :id=>"hbt_sobrenosotros" %>
    <div class="dropmenu sobrenosotros">
      <%= link_to "Sobre Nosotros", acerca_de_path(:anchor=>"sobre-nosotros") %>
      <%= link_to "Nuestros Servicios", acerca_de_path(:anchor=>"nuestros-servicios") %>
      <%= link_to "Certificaciones", acerca_de_path(:anchor=>"certificaciones") %>
      <%= link_to "Casos de Éxito", acerca_de_path(:anchor=>"casos") %>
    </div>
  </span>

  <span class="hbtwrapper">
    <%= link_to "Servicios Web", web_path(:anchor=>"head"), :class=>(controller.controller_name=="servicios_web" ? "hbt active" : "hbt"), :id=>"hbt_web" %>
    <div class="dropmenu web">
      <%= link_to "Dominios", web_path(:anchor=>"dominios") %>
      <%= link_to "Hosting (Alojamiento Web)", web_path(:anchor=>"hosting")%>
      <%= link_to "Transferencia de Correos", web_path(:anchor=>"correos-transfer")%>
      <%= link_to "Desarrollo y Diseño Web", web_path(:anchor=>"webdev"), :class=>"smooth" %>
      <%= link_to "Alojamiento y Streaming de Medios", web_path(:anchor=>"streaming")%>
      <%= link_to "Envío de Correos Masivo", web_path(:anchor=>"correos-masivo")%>
    </div>
  </span>

  <span class="hbtwrapper">
    <%= link_to "Soluciones Cloud", cloud_path(:anchor=>"head"), :class=>(controller.controller_name=="soluciones_cloud" ? "hbt active" : "hbt"), :id=>"hbt_cloud" %>
    <div class="dropmenu cloud">
      <%= link_to "Servidores Privados Virtuales (VPS)", cloud_path(:anchor=>"vps") %>
      <%= link_to "Hosting en VPS (Cloud Hosting)", cloud_path(:anchor=>"cloud-hosting") %>
      <%= link_to "Gaming Servers", cloud_path(:anchor=>"gaming-servers") %>
      <%= link_to "Telefonía IP en la Nube", cloud_path(:anchor=>"tel-ip-nube") %>
      <%= link_to "Contabilidad en la Nube", cloud_path(:anchor=>"contabilidad-nube") %>
    </div>
  </span>

  <span class="hbtwrapper">
    <%= link_to "Proyectos TIC", tic_path(:anchor=>"head"), :class=>(controller.controller_name=="proyectos_tic" ? "hbt active" : "hbt"), :id=>"hbt_tic" %>
    <div class="dropmenu tic">
      <%= link_to "Asesoría", tic_path(:anchor=>"asesoria") %>
      <%= link_to "Consultoría", tic_path(:anchor=>"consultoria") %>
      <%= link_to "Tercerización", tic_path(:anchor=>"tercerizacion") %>
      <%= link_to "Servidores Linux", tic_path(:anchor=>"servidores-linux") %>
      <%= link_to "Redes", tic_path(:anchor=>"redes") %>
      <%= link_to "Telefonía IP", tic_path(:anchor=>"telefonia-ip") %>
    </div>
  </span>

</div>

app/views/layouts/_headerbottomtabs.mobile.erb
<div id="headerbottomtabs">

  <span class="hbtwrapper">
    <%= link_to "Quiénes Somos", "javascript:void(0);", :class=>(controller.controller_name=="acerca_de" ? "hbt active" : "hbt"), :id=>"hbt_sobrenosotros" %>
    <div class="dropmenu sobrenosotros">
      <%= link_to "Sobre Nosotros", acerca_de_path(:anchor=>"sobre-nosotros") %>
      <%= link_to "Nuestros Servicios", acerca_de_path(:anchor=>"nuestros-servicios") %>
      <%= link_to "Certificaciones", acerca_de_path(:anchor=>"certificaciones") %>
      <%= link_to "Casos de Éxito", acerca_de_path(:anchor=>"casos") %>
    </div>
  </span>

  <span class="hbtwrapper">
    <%= link_to "Servicios Web", "javascript:void(0);", :class=>(controller.controller_name=="servicios_web" ? "hbt active" : "hbt"), :id=>"hbt_web" %>
    <div class="dropmenu web">
      <%= link_to "Dominios", web_path(:anchor=>"dominios") %>
      <%= link_to "Hosting (Alojamiento Web)", web_path(:anchor=>"hosting")%>
      <%= link_to "Transferencia de Correos", web_path(:anchor=>"correos-transfer")%>
      <%= link_to "Desarrollo y Diseño Web", web_path(:anchor=>"webdev"), :class=>"smooth" %>
      <%= link_to "Alojamiento y Streaming de Medios", web_path(:anchor=>"streaming")%>
      <%= link_to "Envío de Correos Masivo", web_path(:anchor=>"correos-masivo")%>
    </div>
  </span>

  <span class="hbtwrapper">
    <%= link_to "Soluciones Cloud", "javascript:void(0);", :class=>(controller.controller_name=="soluciones_cloud" ? "hbt active" : "hbt"), :id=>"hbt_cloud" %>
    <div class="dropmenu cloud">
      <%= link_to "Servidores Privados Virtuales (VPS)", cloud_path(:anchor=>"vps") %>
      <%= link_to "Hosting en VPS (Cloud Hosting)", cloud_path(:anchor=>"cloud-hosting") %>
      <%= link_to "Gaming Servers", cloud_path(:anchor=>"gaming-servers") %>
      <%= link_to "Telefonía IP en la Nube", cloud_path(:anchor=>"tel-ip-nube") %>
      <%= link_to "Contabilidad en la Nube", cloud_path(:anchor=>"contabilidad-nube") %>
    </div>
  </span>

  <span class="hbtwrapper">
    <%= link_to "Proyectos TIC", "javascript:void(0);", :class=>(controller.controller_name=="proyectos_tic" ? "hbt active" : "hbt"), :id=>"hbt_tic" %>
    <div class="dropmenu tic">
      <%= link_to "Asesoría", tic_path(:anchor=>"asesoria") %>
      <%= link_to "Consultoría", tic_path(:anchor=>"consultoria") %>
      <%= link_to "Tercerización", tic_path(:anchor=>"tercerizacion") %>
      <%= link_to "Servidores Linux", tic_path(:anchor=>"servidores-linux") %>
      <%= link_to "Redes", tic_path(:anchor=>"redes") %>
      <%= link_to "Telefonía IP", tic_path(:anchor=>"telefonia-ip") %>
    </div>
  </span>

</div>

app/views/layouts/_headertoptabs.html.erb
<div id="headertop"><div class="wrapper">

  <a href="<%= enlaces_path(:anchor=>'head') %>" class="<%= (controller.controller_name=='enlaces') ? 'shiny active' : 'shiny' %>">
    <%= image_tag "icon_enlaces.png" %>
    Enlaces de Interés
  </a>
  <a href="<%= soporte_path(:anchor=>'head') %>" class="<%= (controller.controller_name=='soporte') ? 'shiny active' : 'shiny' %>">
    <%= image_tag "icon_soporte.png" %>
    Soporte & Descargas
  </a>
  <a href="<%= contacto_path(:anchor=>'head') %>" class="<%= (controller.controller_name=='contacto') ? 'shiny active' : 'shiny' %>">
    <%= image_tag "icon_contacto.png" %>
    Contacto
  </a>

</div></div>

app/views/layouts/_headertoptabs.mobile.erb
<div id="headertop"><div class="wrapper">

  <a href="<%= enlaces_path(:anchor=>'head') %>" class="<%= (controller.controller_name=='enlaces') ? 'shiny active' : 'shiny' %>">
    <%= image_tag "icon_enlaces.png" %>
    Enlaces de Interés
  </a>
  <a href="<%= soporte_path(:anchor=>'head') %>" class="<%= (controller.controller_name=='soporte') ? 'shiny active' : 'shiny' %>">
    <%= image_tag "icon_soporte.png" %>
    Soporte & Descargas
  </a>
  <a href="<%= contacto_path(:anchor=>'head') %>" class="<%= (controller.controller_name=='contacto') ? 'shiny active' : 'shiny' %>">
    <%= image_tag "icon_contacto.png" %>
    Contacto
  </a>

</div></div>

app/views/layouts/_slider.html.erb
<div class="flexslider">
  <ul class="slides">
    <li>
      <%= image_tag "slide_dx.jpg" %>
      <div class="slideinfowrapper"><div class="slideinfo dx">
        <%= link_to image_tag("logo_sphere.png"), acerca_de_path(:anchor=>"head") %>
      </div></div>
    </li>
    <li>
      <%= image_tag "slide_web.jpg" %>
      <div class="slideinfowrapper"><div class="slideinfo web">
        <h2>SERVICIOS WEB</h2>
        <h3></h3>
        <div class="slideinfobutton"><%= link_to "VER MÁS", web_path(:anchor=>"head") %></div>
      </div></div>
    </li>
    <li>
      <%= image_tag "slide_webdev.jpg" %>
      <div class="slideinfowrapper"><div class="slideinfo webdev">
        <h2>DESARROLLO Y DISEÑO WEB</h2>
        <div class="slideinfobutton"><%= link_to "VER MÁS", web_path(:anchor=>"webdev") %></div>
      </div></div>
    </li>
    <li>
      <%= image_tag "slide_cloud.jpg" %>
      <div class="slideinfowrapper"><div class="slideinfo cloud">
        <h2>SOLUCIONES CLOUD</h2>
        <h3></h3>
      </div></div>
    </li>
    <li>
      <%= image_tag "slide_tic.jpg" %>
      <div class="slideinfowrapper"><div class="slideinfo tic">
        <h2>PROYECTOS TIC</h2>
        <h3></h3>
      </div></div>
    </li>
  </ul>
</div>

app/views/layouts/_stickyheader.html.erb
<% if %(enlaces soporte contacto).include? controller.controller_name %>

  <div id="headertabsSTICKYwrapper" class="<%= controller.controller_name=='home' ? '' : 'nothome' %>"><div class="headertabsSTICKY">
    <%= link_to "&nbsp;".html_safe, root_path(:anchor=>"head"), :class=>"home" %>
    <%= link_to "Enlaces de Interés", enlaces_path(:anchor=>"head"), :class=>(controller.controller_name=="enlaces" ? "current enlaces" : "enlaces") %>
    <%= link_to "Soporte & Descargas", soporte_path(:anchor=>"head"), :class=>(controller.controller_name=="soporte" ? "current soporte" : "soporte") %>
    <%= link_to "Contacto", contacto_path(:anchor=>"head"), :class=>(controller.controller_name=="contacto" ? "current contacto" : "contacto") %>
  </div></div>

<% else %>

  <div id="headertabsSTICKYwrapper" class="<%= controller.controller_name=='home' ? '' : 'nothome' %>"><div class="headertabsSTICKY">
    <%= link_to "&nbsp;".html_safe, root_path(:anchor=>"head"), :class=>"home" %>
    <%= link_to "Quiénes Somos", acerca_de_path(:anchor=>"head"), :class=>(controller.controller_name=="acerca_de" ? "current acercade" : "acercade") %>
    <%= link_to "Servicios Web", web_path(:anchor=>"head"), :class=>(controller.controller_name=="servicios_web" ? "current web" : "web") %>
    <%= link_to "Soluciones Cloud", cloud_path(:anchor=>"head"), :class=>(controller.controller_name=="soluciones_cloud" ? "current cloud" : "cloud") %>
    <%= link_to "Proyectos TIC", tic_path(:anchor=>"head"), :class=>(controller.controller_name=="proyectos_tic" ? "current tic last" : "tic last") %>
  </div></div>

<% end %>